[WIP] hw04: Array
hrvchnk/prjctr-hw pull request #4
Opened 2024-11-21 16:45 UTC by hrvchnk

1. Задача на повернення ініціалів для кожного імені з масиву, посортованих в алфавітному порядку: 
Рішення має працювати незалежно від конкретних значень в масиві імен
const userNames = ["Петрик Ольга Іванівна", "Гнатюк Петро Антонович", "Рудко Андрій Опанасович"];
let initials;
// тут ваш код ...
console.log(initials); // [ "Г.П.А.", "П.О.І.", "Р.А.О."]

2. Задача на фільтрування масиву
Реалізуйте фільтрування імен які починаються з голосної двома способами:
-через умовну конструкцію
-через вбудований метод масивів
Рішення має працювати незалежно від конкретних значень в масиві імен
const userNames = ['Петро', 'Емма', 'Юстин', 'Ілля', 'Марта', 'Яна', 'Василь', 'Антон', 'Олена'];
let filteredNames;
// тут ваш код...
console.log(filteredNames); // ['Емма', 'Юстин', 'Ілля', 'Яна', 'Антон', 'Олена']

3. Задача на розворот числа:
const currentMaxValue = 4589;
let reverseMaxValue;
// тут ваш код...
console.log(reverseMaxValue); // 9854
console.log(typeof reverseMaxValue); // 'number'

4. Задача на знаходження добутку масиву чисел з невідомою глибиною вкладеності:
const resultsArray = [1, 2, [3, [4]]];
let productOfArray;
// тут ваш код...
console.log(productOfArray); // 24

2024-11-22 18:57 UTC, myroslav-kolomiiets requested changes

2024-11-22 18:57 UTC, myroslav-kolomiiets commented on hw04/index.js
> +
```suggestion
function convertValueStrToNumber(value) {
  return Number(value.toString().split('').reverse().join(''));
}
```
Тут неоправдано роздуте рішення, все це можна звести до одніє подібної функції. Краще уникати свідомого переускладнення коду. Чим простіше, тим краще, при однаковому результаті.

2024-11-22 18:57 UTC, myroslav-kolomiiets commented on hw04/index.js
> +	return number;
```suggestion
	return getFlattenArray(arr).reduce((a, b) => a * b);
```
Змінна number тут лишня

2024-11-22 18:57 UTC, myroslav-kolomiiets commented on hw04/index.js
> +	return arr.flat(2);
По умові треба врахувати, що глибина вкладеності нам не відома, а це рішення тільки для однієї вкладеності

2024-11-23 12:13 UTC, hrvchnk commented on hw04/index.js
> +
мало досвіду роботи з функціями і їх взаємодія, хотів в задачі використати і роботу з циклами, і роботу з функціями побільше :)

2024-11-23 12:15 UTC, hrvchnk commented on hw04/index.js
> +	return arr.flat(2);
тобто, це не .flat(2), а .flat(infinity) ?

2024-11-25 17:12 UTC, myroslav-kolomiiets requested changes
Залиш в пул реквесті тільки те що йде на перевірку. Якщо в задачі вказано що треба надати два варіанти рішення, значить два. У всіх інших випадках має бути одне. Закоментованого коду, чернеток, записів тощо, у ДЗ бути не повинно.

2024-11-28 19:39 UTC, myroslav-kolomiiets approved these changes

2024-11-29 12:30 UTC, merged